### ISSUE TITLE
macOS demo

### ISSUE THREAD

**Issue by Bill-Costa** [ddmitov/perl-executing-browser#11]
Surprised that there is no macOS demo.  Is this mostly because the authors do not have access to that platform?

**Comment by ddmitov** [comment]
Dear Bill-Costa,

At the time of this writing, I don't have access to any Mac and I cannot develop or test on this platform, but some years ago Valcho Nedelchev tested successfully the perl-executing-browser on a Mac machine. Provided that you have Qt development bundle versions 5.2 - 5.5 for Mac and you don't make a Mac bundle after the PEB binary is compiled, so that PEB will be able to find its default directories, it should be possible to compile PEB for Mac.

Unfortunately, all PEB-compatible Qt development bundle versions, a bit old now, are removed even from the Qt Archive at https://download.qt.io/archive/qt/. If you can not find any of the compatible Qt development bundles for Mac (I don't have them either), you could take a look at an experimental version of PEB called Perl Executing Browser QtWebEngine -  https://github.com/ddmitov/perl-executing-browser-qtwebengine. At least theoretically, this version of PEB could be compiled on a Mac machine with a more recent Qt version, but this was never tested due to lack of development machine and interest.

I hope this is not to discouraging for you! In case of development interest for a Mac version of PEB using a recent Qt version, I could un-archive the Perl Executing Browser QtWebEngine.

With all my best wishes,
Dimitar Mitov

**Comment by Bill-Costa** [comment]
Thanks for the thoughtful reply. Building a macOS/Linux/Windows tri-boot system on an old laptop has been on my list of things to do.  I'll do that real-soon-now(tm) then I can kick the tires on the PEB demo on both Linux and Windows.  That will help me decide if I want to dive into attempting a macOS port.  Thanks again for the background info.
